### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by mk-pmb** [kba/anno-frontend#29]
Hi! What's the license status of the files in this project? I assume all MIT? Could you declare that, and your preferred attribution (e.g. author name), in package.json and maybe also in a LICENSE.txt?
GitHub currently confuses the CC license config for a repo license, but I don't think it's meant as that.

**Comment by kba** [comment]
`MIT` is fine.

**Comment by mk-pmb** [comment]
Thanks! :+1:
